version: '3.8'
services:
  test-db:
    image: postgres:16-alpine
    container_name: testdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8081:5432'
    volumes:
      - test-db:/var/lib/postgresql/data
volumes:
  test-db:
    driver: local