region_location = {
    "top_left_region": "South",
    "bottom_left_region": "West",
    "top_right_region": "East",
    "bottom_right_region": "Midwest",
}

south = {
    1: "Auburn",
    2: "Michigan State",
    3: "Iowa State",
    4: "Texas A&M",
    5: "Michigan",
    6: "Mississippi",
    7: "Marquette",
    8: "Louisville",
    9: "Creighton",
    10: "New Mexico",
    11: "SDSU",
    12: "UCSD",
    13: "Yale",
    14: "Lipscomb",
    15: "Bryant",
    16: "Alabama State",
    "play_in": "UNC",
    "play_in_rank": 11,
}

east = {
    1: "Duke",
    2: "Alabama",
    3: "Wisconsin",
    4: "Arizona",
    5: "Oregon",
    6: "BYU",
    7: "St. Mary's",
    8: "Mississippi State",
    9: "Baylor",
    10: "Vanderbilt",
    11: "VCU",
    12: "Liberty",
    13: "Akron",
    14: "Montana",
    15: "Robert Morris",
    16: "American",
    "play_in": "Mount St. Mary's",
    "play_in_rank": 16,
}

midwest = {
    1: "Houston",
    2: "Tennessee",
    3: "Kentucky",
    4: "Purdue",
    5: "Clemson",
    6: "Illinois",
    7: "UCLA",
    8: "Gonzaga",
    9: "Georgia",
    10: "Utah State",
    11: "Texas",
    12: "McNeese State",
    13: "High Point",
    14: "Troy",
    15: "Wofford",
    16: "SIUE",
    "play_in": "Xavier",
    "play_in_rank": 11,
}

west = {
    1: "Florida",
    2: "St. John's",
    3: "Texas Tech",
    4: "Maryland",
    5: "Memphis",
    6: "Missouri",
    7: "Kansas",
    8: "UConn",
    9: "Oklahoma",
    10: "Arkansas",
    11: "Drake",
    12: "CSU",
    13: "Grand Canyon",
    14: "UNC Wilmington",
    15: "Nebraska Omaha",
    16: "Norfolk State",
    "play_in": "Norfolk State",
    "play_in_rank": 16,
}
