# Generated by Django 4.2.6 on 2024-08-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("region", models.CharField(max_length=30)),
                ("first_four_winner", models.CharField(max_length=58)),
            ],
            options={
                "db_table": "marchmadness_group",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=58, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("formal_name", models.CharField(max_length=69)),
                ("nickname", models.CharField(max_length=30)),
                ("home_arena", models.CharField(max_length=60, null=True)),
                ("conference", models.CharField(max_length=30)),
                ("tournament_appearances", models.IntegerField(default=0)),
                ("final_four_appearances", models.IntegerField(default=0)),
                ("championship_wins", models.IntegerField(default=0)),
                ("primary_color", models.CharField(max_length=20, null=True)),
                ("secondary_color", models.CharField(max_length=20, null=True)),
                ("location", models.CharField(max_length=50, null=True)),
                ("is_private", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "marchmadness_school",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "year",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("left_top_region", models.CharField(max_length=30)),
                ("left_bottom_region", models.CharField(max_length=30)),
                ("right_top_region", models.CharField(max_length=30)),
                ("right_bottom_region", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "marchmadness_tournament",
            },
        ),
        migrations.CreateModel(
            name="TournamentRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=58)),
                ("ranking", models.IntegerField()),
                ("region", models.CharField(max_length=30)),
                ("play_in", models.BooleanField(default=False)),
                ("year", models.IntegerField()),
            ],
            options={
                "db_table": "marchmadness_tournamentranking",
                "unique_together": {("school_name", "year")},
            },
        ),
        migrations.CreateModel(
            name="Rivalry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=58)),
                ("team2", models.CharField(max_length=58)),
            ],
            options={
                "db_table": "marchmadness_rivalry",
                "unique_together": {("team1", "team2")},
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("season", models.CharField(max_length=9)),
                ("school_name", models.CharField(max_length=58)),
                ("opponent", models.CharField(max_length=58)),
                ("school_score", models.IntegerField()),
                ("opponent_score", models.IntegerField()),
                ("home_game", models.BooleanField(default=True)),
                ("win", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "marchmadness_game",
                "unique_together": {
                    (
                        "date",
                        "school_name",
                        "opponent",
                        "school_score",
                        "opponent_score",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "year",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "left_bottom_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_bottom_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "left_top_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_top_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "right_bottom_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_bottom_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "right_top_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_top_group",
                        to="marchmadness.group",
                    ),
                ),
            ],
            options={
                "db_table": "marchmadness_bracket",
            },
        ),
        migrations.CreateModel(
            name="APRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=58)),
                ("ranking", models.IntegerField()),
                ("year", models.IntegerField()),
            ],
            options={
                "db_table": "marchmadness_apranking",
                "unique_together": {("school_name", "year"), ("ranking", "year")},
            },
        ),
    ]
