# Generated by Django 4.2.6 on 2024-08-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0013_rename_conference_tournamentranking_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("region", models.CharField(max_length=30)),
                ("first_four_winner", models.CharField(max_length=58)),
                ("w_first_1_16", models.CharField(max_length=58)),
                ("w_first_2_15", models.CharField(max_length=58)),
                ("w_first_3_14", models.CharField(max_length=58)),
                ("w_first_4_13", models.CharField(max_length=58)),
                ("w_first_5_12", models.CharField(max_length=58)),
                ("w_first_6_11", models.CharField(max_length=58)),
                ("w_first_7_10", models.CharField(max_length=58)),
                ("w_first_8_9", models.CharField(max_length=58)),
                ("w_second_1_8", models.CharField(max_length=58)),
                ("w_second_2_7", models.CharField(max_length=58)),
                ("w_second_3_6", models.CharField(max_length=58)),
                ("w_second_4_5", models.CharField(max_length=58)),
                ("w_sweet_1_4", models.CharField(max_length=58)),
                ("w_sweet_2_3", models.CharField(max_length=58)),
                ("group_winner", models.CharField(max_length=58)),
            ],
            options={
                "db_table": "marchmadness_group",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "year",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("top_left_region", models.CharField(max_length=30)),
                ("bottom_left_region", models.CharField(max_length=30)),
                ("top_right_region", models.CharField(max_length=30)),
                ("bottom_right_region", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "marchmadness_tournament",
            },
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(
                max_length=58, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apranking",
            unique_together={("ranking", "year"), ("school_name", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="game",
            unique_together={
                ("date", "school_name", "opponent", "school_score", "opponent_score")
            },
        ),
        migrations.AlterUniqueTogether(
            name="rivalry",
            unique_together={("team1", "team2")},
        ),
        migrations.AlterUniqueTogether(
            name="tournamentranking",
            unique_together={("school_name", "year")},
        ),
        migrations.AlterModelTable(
            name="apranking",
            table="marchmadness_apranking",
        ),
        migrations.AlterModelTable(
            name="game",
            table="marchmadness_game",
        ),
        migrations.AlterModelTable(
            name="rivalry",
            table="marchmadness_rivalry",
        ),
        migrations.AlterModelTable(
            name="school",
            table="marchmadness_school",
        ),
        migrations.AlterModelTable(
            name="tournamentranking",
            table="marchmadness_tournamentranking",
        ),
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("season", models.CharField(max_length=9)),
                (
                    "bottom_left_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bottom_left_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "bottom_right_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bottom_right_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "top_left_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_left_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "top_right_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_right_group",
                        to="marchmadness.group",
                    ),
                ),
            ],
            options={
                "db_table": "marchmadness_bracket",
            },
        ),
    ]
