# Generated by Django 4.2.6 on 2024-08-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0014_group_tournament_alter_school_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="champion",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="left_winner",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="right_winner",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
