# Generated by Django 4.2.6 on 2024-08-30 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0015_tournament_champion_tournament_left_winner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="group_winner",
            new_name="winner",
        ),
    ]
