# Generated by Django 4.2.6 on 2024-08-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0015_remove_tournament_id_alter_school_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("region", models.CharField(max_length=30)),
                ("first_four_winner", models.CharField(max_length=58)),
            ],
            options={
                "db_table": "marchmadness_group",
            },
        ),
        migrations.AlterModelTable(
            name="apranking",
            table="marchmadness_apranking",
        ),
        migrations.AlterModelTable(
            name="game",
            table="marchmadness_game",
        ),
        migrations.AlterModelTable(
            name="rivalry",
            table="marchmadness_rivalry",
        ),
        migrations.AlterModelTable(
            name="school",
            table="marchmadness_school",
        ),
        migrations.AlterModelTable(
            name="tournament",
            table="marchmadness_tournament",
        ),
        migrations.AlterModelTable(
            name="tournamentranking",
            table="marchmadness_tournamentranking",
        ),
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "year",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "left_bottom_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_bottom_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "left_top_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_top_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "right_bottom_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_bottom_group",
                        to="marchmadness.group",
                    ),
                ),
                (
                    "right_top_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_top_group",
                        to="marchmadness.group",
                    ),
                ),
            ],
            options={
                "db_table": "marchmadness_bracket",
            },
        ),
    ]
