# Generated by Django 4.2.6 on 2024-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0016_group_alter_apranking_table_alter_game_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_winner",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_first_1_16",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_first_2_15",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_first_3_14",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_first_4_13",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_first_5_12",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_first_6_11",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_first_7_10",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_first_8_9",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_second_1_8",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_second_2_7",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_second_3_6",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_second_4_5",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_sweet_1_4",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="w_sweet_2_3",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
    ]
