# Generated by Django 4.2.6 on 2024-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0016_rename_group_winner_group_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="champion",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bracket",
            name="left_winner",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bracket",
            name="right_winner",
            field=models.CharField(default="", max_length=58),
            preserve_default=False,
        ),
    ]
