# Generated by Django 4.2.6 on 2024-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0016_group_alter_apranking_table_alter_game_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="season",
            field=models.CharField(default=-1, max_length=9),
            preserve_default=False,
        ),
    ]
