# Generated by Django 4.2.6 on 2024-08-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0017_group_group_winner_group_w_first_1_16_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="left_bottom_region",
            new_name="bottom_left_region",
        ),
        migrations.RenameField(
            model_name="tournament",
            old_name="right_bottom_region",
            new_name="bottom_right_region",
        ),
        migrations.RenameField(
            model_name="tournament",
            old_name="left_top_region",
            new_name="top_left_region",
        ),
        migrations.RenameField(
            model_name="tournament",
            old_name="right_top_region",
            new_name="top_right_region",
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="left_bottom_group",
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="left_top_group",
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="right_bottom_group",
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="right_top_group",
        ),
        migrations.AddField(
            model_name="bracket",
            name="bottom_left_group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bottom_left_group",
                to="marchmadness.group",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bracket",
            name="bottom_right_group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bottom_right_group",
                to="marchmadness.group",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bracket",
            name="top_left_group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top_left_group",
                to="marchmadness.group",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bracket",
            name="top_right_group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top_right_group",
                to="marchmadness.group",
            ),
            preserve_default=False,
        ),
    ]
