# Generated by Django 4.2.6 on 2024-08-30 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0017_bracket_champion_bracket_left_winner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="first_four_winner",
            new_name="four_winner",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_first_1_16",
            new_name="w_1_16",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_first_2_15",
            new_name="w_1_4",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_first_3_14",
            new_name="w_1_8",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_first_4_13",
            new_name="w_2_15",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_first_5_12",
            new_name="w_2_3",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_first_6_11",
            new_name="w_2_7",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_first_7_10",
            new_name="w_3_14",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_first_8_9",
            new_name="w_3_6",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_second_1_8",
            new_name="w_4_13",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_second_2_7",
            new_name="w_4_5",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_second_3_6",
            new_name="w_5_12",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_second_4_5",
            new_name="w_6_11",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_sweet_1_4",
            new_name="w_7_10",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="w_sweet_2_3",
            new_name="w_8_9",
        ),
    ]
